DOMAIN_EXTENSIONS_TO_CHECK = [".com"]
LUCKY_GUESS_MIN_VALUE = 1000
PERIODIC_LUCKY_SHOT_TIME = 3600  # In seconds
LUCKY_GUESS_TOPICS = [
    "Real Estate Development",
    "Commercial Real Estate",
    "Residential Real Estate",
    "Luxury Real Estate",
    "Mortgage",
    "Banking",
    "Investment Banking",
    "Private Equity",
    "Venture Capital",
    "Hedge Funds",
    "Stocks",
    "Bonds",
    "Mutual Funds",
    "Exchange Traded Funds",
    "Retirement Planning",
    "Wealth Management",
    "Health Insurance",
    "Auto Insurance",
    "Life Insurance",
    "Property and Casualty Insurance",
    "Telecommunications",
    "Cloud Computing",
    "Artificial Intelligence",
    "Machine Learning",
    "Data Science",
    "Cybersecurity",
    "Virtual Reality",
    "Augmented Reality",
    "Video Games",
    "Film",
    "Television",
    "Music",
    "Theater",
    "Healthcare Services",
    "Hospitals",
    "Medical Clinics",
    "Mental Health",
    "Telehealth",
    "Telemedicine",
    "Pharmaceuticals",
    "Biotechnology",
    "Medical Devices",
    "Energy",
    "Environmental",
    "Logistics",
    "Shipping",
    "Aviation",
    "Construction",
    "Engineering",
    "Architecture",
    "Investing",
    "Management",
    "Hospitality",
    "Human Resources",
    "Retail",
    "E-commerce",
    "Social Media",
    "Software",
    "Hardware",
    "Marketing",
    "Consulting",
    "Law",
    "Media",
    "Education",
    "Fitness",
    "Sports",
    "Travel",
    "Fashion",
    "Gaming",
    "Entertainment",
    "Food and Drink",
    "Pets",
    "Beauty",
    "Home Improvement",
    "Photography",
    "Real Estate",
    "Automotive",
    "Technology",
    "Telephony",
    "Wireless",
    "Internet",
    "Domain Names",
    "Advertising",
    "Publishing",
    "Bankruptcy",
    "Credit Counseling",
    "Debt Consolidation",
    "Investment News",
    "Job Search",
    "Marketing Strategy",
    "Multimedia",
    "Public Relations",
    "Search Engine Optimization",
    "Social Networking",
    "Web Hosting",
]
