DOMAIN_EXTENSIONS_TO_CHECK = [".com", ".io", ".ai"]
LUCKY_GUESS_MIN_VALUE = 100
PERIODIC_LUCKY_SHOT_TIME = 3600  # In seconds
LUCKY_GUESS_TOPICS = [
    "Cryptocurrency",
    "Blockchain",
    "Fitness",
    "Health",
    "Yoga",
    "Meditation",
    "Travel",
    "Food",
    "Cooking",
    "Beauty",
    "Fashion",
    "Photography",
    "Design",
    "Web development",
    "Programming",
    "Education",
    "Online learning",
    "Finance",
    "Investing",
    "Real estate",
    "Music",
    "Art",
    "Writing",
    "Blogging",
    "E-commerce",
    "Marketing",
    "Social media",
    "Technology",
    "Gadgets",
    "Gaming",
    "Sports",
    "Outdoor activities",
    "Pets",
    "Children",
    "Parenting",
    "Green living",
    "Sustainability",
    "DIY",
    "Home improvement",
    "Gardening",
    "Personal development",
    "Spirituality",
    "Mindfulness",
    "Wellness",
    "Self-help",
    "Business",
    "Entrepreneurship",
    "Leadership",
    "Management",
    "Sales",
    "Customer service",
    "Human resources",
    "Project management",
    "Time management",
    "Productivity",
    "Career development",
    "Job search",
    "Job interviews",
    "Freelancing",
    "Consulting",
    "Coaching",
    "Mentoring",
    "Public speaking",
    "Event planning",
    "Wedding planning",
    "Dating",
    "Relationships",
    "Marriage",
    "Retirement",
    "Travel blogging",
    "Food blogging",
    "Fashion blogging",
    "Lifestyle blogging",
    "Beauty blogging",
    "Personal finance",
    "Budgeting",
    "Saving money",
    "Credit cards",
    "Debt management",
    "Insurance",
    "Taxes",
    "Investing in stocks",
    "Investing in real estate",
    "Investing in mutual funds",
    "Investing in cryptocurrencies",
    "Trading",
    "Online education",
    "Online business",
    "Online marketing",
    "Online advertising",
    "SEO",
    "PPC",
    "Affiliate marketing",
    "Email marketing",
    "Content marketing",
    "Social media marketing",
    "Influencer marketing",
]
